# Generated by Django 3.0.6 on 2020-05-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'ordering': ['title'], 'verbose_name': 'AboutMe', 'verbose_name_plural': 'AboutMe'},
        ),
        migrations.AddField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(blank=True, upload_to='about', verbose_name='imagen'),
        ),
    ]
