# Generated by Django 3.0.6 on 2020-05-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='footer', verbose_name='imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha modificacion')),
            ],
            options={
                'verbose_name': 'foto_pie',
                'verbose_name_plural': 'fotos_pie',
                'ordering': ['-created'],
            },
        ),
    ]
